### ISSUE TITLE
IonToExcel `from must not be blank` error

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-serdes#155]
### Describe the issue

```yaml
id: ion_to_excel
namespace: qa
variables:
  sheet_title: my_sheet-123
tasks:
  - id: create_csv
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: convert_to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ outputs.create_csv.uri}}"


  - id: convert_to_excel
    type: io.kestra.plugin.serdes.excel.IonToExcel
    from: "{{ outputs.convert_to_ion.uri}}"
    sheetsTitle: "{{ vars.sheet_title }}"

    
  - id: excel_to_ion
    type: io.kestra.plugin.serdes.excel.ExcelToIon
    from: "{{ outputs.convert_to_excel.uri }}"
    sheetsTitle: 
      - "{{ vars.sheet_title }}"
```

![image](https://github.com/user-attachments/assets/402cbceb-c115-4cb8-ae94-27203d739428)

### Environment

- Kestra Version: develop
