### ISSUE TITLE
IonToJson requires x8-x10 more RAM then inital file size

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/plugin-serdes#164]
### Describe the issue

On my VM with 8 CPU and 8 GB RAM io.kestra.plugin.serdes.json.IonToJson can convert a 600 Mb file in 2 minutes, but a 1 Gb file fails with a Java heap space error after 40 minutes. During this period, UI almost doesn't work and new flows don't start by schedule.

I use `- JAVA_OPTS=-Xms4G -Xmx6G` config.

flow that I run
```
- id: getParams
    type: io.kestra.plugin.jdbc.sqlserver.Queries
    url: jdbc:sqlserver://;trustServerCertificate=true
    username: 
    password: 
    sql: |
      DECLARE @DateFrom DATE = '2024-12-01'
        , @DateTo DATE = GETDATE()-1
      EXEC [DataBase].[dbo].[sp_Test] @DateFrom = @DateFrom, @DateTo = @DateTo;
    fetchType: STORE
  - id: resultToJson
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.getParams.outputs[0].uri }}"
    newLine: false
```

slack thread with discussion - https://kestra-io.slack.com/archives/C03FQKXRK3K/p1738239094441759

### Environment

- Kestra Version: 0.20.13
