### ISSUE TITLE
alwaysDelimitText setting ignored

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-serdes#181]
### Describe the issue

By default, alwaysDelimitText is set to false, however since 0.21 this is no longer the case. 
```
id: csv
namespace: solutions.demo

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://db:5452
    fetchType: STORE
    sql: |
      select * from kestra.logs
  - id: csv
    type: io.kestra.plugin.serdes.csv.IonToCsv
    alwaysDelimitText: false
    from: "{{outputs.query.uri}}"
```

E.g. in the above, 0.20.19 the string fields will be returned without " characters, however in 0.21 and later all strings are encased in " " 

### Environment

- Kestra Version: develop
