### ISSUE TITLE
Add new serialization tasks for converting to and from markdown to different formats (HTML, plain text)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-serdes#187]
### Feature description

Often, many tasks (e.g., LLM plugins) return markdown. When you try to use that output directly in a follow up notification task (e.g. Slack, email), you will end up either in:

1. Error -- Slack https://github.com/kestra-io/plugin-notifications/issues/227
2. Unreadable format -- Email - see tha image at the bottom of the issue

It would be helpful to add new conversion tasks to help translate between such text formats:
- [ ] `io.kestra.plugin.serdes.markdown.MarkdownToHtml` - turns markdown special characters so that the file will be rendered the same way but using HTML syntax,  -- useful to pass that into htmlTextContext in Mail task with no ugly display
- [ ] `io.kestra.plugin.serdes.markdown.MarkdownToText` - strips any special characters and keeps only the plain text (expected to lose some information like URLs, header info, bold/italic syntax etc.) -- useful to pass that into raw JSON payload with no dirty escaping or parsing errors

Examples:

```yaml
id: serdes
namespace: company.team

tasks:
  - id: openai
    type: io.kestra.plugin.core.output.OutputValues
    values:
      markdown: |
        1. **Margot Friedländer, Holocaust Survivor, Passes Away at 103** Margot Friedländer, a Holocaust survivor and prominent figure in Germany's remembrance culture, has died at the age of 103. She was honored at a ceremony in Berlin, where President Frank-Walter Steinmeier and Chancellor Friedrich Merz paid tribute to her contributions to promoting reconciliation and preserving the memory of Nazi atrocities. ([reuters.com](https://www.reuters.com/world/europe/germany-lays-rest-margot-friedlaender-holocaust-survivor-key-remembrance-culture-2025-05-15/?utm_source=openai)) 
        2. **Cirque du Soleil Announces First Permanent European Show in Berlin** Cirque du Soleil has chosen Berlin's Potsdamer Platz as the venue for its first permanent European show, titled "Alize," set to begin in November 2025. The production will transform the Theater at Potsdamer Platz to accommodate its unique technical needs, offering audiences a blend of acrobatic acts, magic, and artistry. ([reuters.com](https://www.reuters.com/lifestyle/cirque-du-soleil-picks-berlin-first-permanent-european-show-2024-11-20/?utm_source=openai)) 
        3. **Berlin's Arts Scene Faces Severe Budget Cuts** Berlin's arts community is confronting significant budget cuts, with the city's government planning to reduce next year's arts budget by €130 million as part of a broader austerity measure. This has led to protests and concerns about the impact on major institutions and the independent arts scene. ([ft.com](https://www.ft.com/content/37e19262-ccba-4d87-b825-929c998f5872?utm_source=openai)) 
        4. **Former East German Secret Police Officer Sentenced for 1974 Border Killing** An 80-year-old former Stasi officer has been sentenced to 10 years in prison for the 1974 murder of Polish citizen Czesław Kukuczka at a Berlin border crossing. The court confirmed that the officer executed the killing under Stasi orders, labeling the act as planned and merciless. ([apnews.com](https://apnews.com/article/8cde4b1a8a6537e841977fc4fc442bcf?utm_source=openai)) 5. **Berlin's Gentrification Alters City's Cultural Landscape** Thirty-five years after the fall of the Berlin Wall, the city is undergoing profound transformations. Once renowned for its vibrant nightlife and counterculture, Berlin is experiencing the closure of iconic institutions due to rising rents and the impact of the COVID-19 pandemic. Gentrification and increased living costs are reshaping the city's identity, challenging its cultural vibrancy. ([lemonde.fr](https://www.lemonde.fr/economie/article/2024/11/09/trente-cinq-ans-apres-la-chute-du-mur-berlin-la-liberale-a-perdu-de-son-eclat_6384637_3234.html?utm_source=openai)) 
        ## Top Berlin News Stories: 
          - [Germany lays to rest Margot Friedlaender, Holocaust survivor key to remembrance culture](https://www.reuters.com/world/europe/germany-lays-rest-margot-friedlaender-holocaust-survivor-key-remembrance-culture-2025-05-15/?utm_source=openai) 
          - [Cirque du Soleil picks Berlin for first permanent European show](https://www.reuters.com/lifestyle/cirque-du-soleil-picks-berlin-first-permanent-european-show-2024-11-20/?utm_source=openai) 
          - [Berlin cries Kulturkrise as cuts hit arts scene](https://www.ft.com/content/37e19262-ccba-4d87-b825-929c998f5872?utm_source=openai)      

  - id: to_ion
    type: io.kestra.plugin.serdes.markdown.MarkdownToHtml
    from: "{{ outputs.openai.uri }}"

  - id: to_ion
    type: io.kestra.plugin.serdes.markdown.MarkdownToText
    from: "{{ outputs.openai.uri }}"
```

![Image](https://github.com/user-attachments/assets/444689df-39cd-4351-8aa6-59c09926b031)
