### ISSUE TITLE
Excel to Ion convert date unexpected

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-serdes#193]
### Describe the issue

You can see with this flow that the column with date field is being converted to datetime.
- It's not explicit, input is data output should date (not datetime)
- It can result in bad datetime conversion (timezone difference, was able to see day minus 1 in the output data...)

[Demo Expense.xlsx](https://github.com/user-attachments/files/20922054/Demo.Expense.xlsx)

![Image](https://github.com/user-attachments/assets/e9386803-a99e-49cf-bf52-af98b5ed1e2a)
![Image](https://github.com/user-attachments/assets/73edac1d-1280-40e3-b1df-d409e7e8244d)

```yaml
id: ostrich_384138
namespace: dev.ben

inputs:
  - id: excel
    type: FILE

tasks:
  - id: excel_to_ion
    type: io.kestra.plugin.serdes.excel.ExcelToIon
    from: "{{ inputs.excel }}"
```

### Environment

- Kestra Version: develop
