### ISSUE TITLE
IonToExcel shows memory issue

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-serdes#68]
### Expected Behavior

Using the `IonToExcel` shows some memory issues.

The current flow is running in parallel with ~10/40mb Excel files

```yaml
id: ExtraccionInformesBancos
namespace: prod.data
labels:
  Origen: FTP Norma43
  Destino: Selene/Compartida/Bancos
inputs:
  - type: STRING
    name: sql
tasks:
  - id: ExtraccionDatos
    type: io.kestra.plugin.jdbc.oracle.Query
    password: "{{namespace.user_bbdd.qonciliador_adm}}"
    sql: "{{inputs.sql}}"
    store: true
    url: "{{namespace.url.kratos}}"
    username: "{{namespace.user_bbdd.qonciliador_adm}}"

  - id: GeneramosInforme
    type: io.kestra.plugin.serdes.excel.IonToExcel
    dateFormat: dd-MM-yyyy
    dateTimeFormat: dd-MM-yyyy'T'HH:mm:ss.SSS[XXX]
    from: "{{outputs.ExtraccionDatos.uri}}"
    header: true
```

![image](https://github.com/kestra-io/plugin-serdes/assets/46634684/0200147c-4c77-4da4-9cd5-2691bf39c5e1)

### Steps To Reproduce

You can find some csv files up to 200mb here if needed https://www.stats.govt.nz/large-datasets/csv-files-for-download/
And Excel file sample (small one) https://go.microsoft.com/fwlink/?LinkID=521962

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
Even large file that exceeds the allowed nr of rows in Excel worked without hitting any memory limits

![image](https://github.com/kestra-io/plugin-serdes/assets/86264395/3cff5512-fff9-4692-9531-88ee834c4dbf)

might be challenging to reproduce 

```yaml
id: parquet_to_excel
namespace: dev

tasks:
  - id: parquet
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL parquet;
      LOAD parquet;
      INSTALL httpfs;
      LOAD httpfs;
      SELECT * from read_parquet('https://huggingface.co/datasets/kestra/datasets/resolve/main/jaffle-large/raw_items.parquet?download=true');
    store: true

  - id: ion_to_excel
    type: io.kestra.plugin.serdes.excel.IonToExcel
    from: "{{ outputs.parquet.uri }}"
```
