### ISSUE TITLE
XmlReader always returns an empty file

### ISSUE THREAD

**Issue by yvrng** [kestra-io/plugin-serdes#69]
### Expected Behavior

When I use the `XmlReader` I want my XML file to be parsed as expected

### Actual Behaviour

The result ION file is empty, whatever the content of `query`

### Environment Information

- Kestra Version: 0.13.4
- Operating System (OS / Docker / Kubernetes): K8S

### Example flow

```yaml
id: empty-xml
namespace: dev.yvrng
inputs:
  - name: from
    type: FILE
tasks:
  - id: read
    type: io.kestra.plugin.serdes.xml.XmlReader
    from: "{{ inputs.from }}"
    query: /root/pokemon
    parserConfiguration:
      forceList:
        - "type"
```
with the following dataset:
```xml
<root>
    <pokemon id="001" name="Bulbasaur">
        <type index="0">grass</type>
        <type index="1">poison</type>
        <height>0.7</height>
        <weight>6.9</weight>
    </pokemon>
    <pokemon id="004" name="Charmander">
        <type index="0">fire</type>
        <height>0.6</height>
        <weight>8.5</weight>
    </pokemon>
    <pokemon id="007" name="Squirtle">
        <type index="0">water</type>
        <height>0.5</height>
        <weight>9.0</weight>
    </pokemon>
</root>
```
